# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('assets/icons/icon.png', 'assets/icons'),
        ('assets/icons/fav/apple-icon-180x180.png', 'assets/icons/fav'),
        ('assets/icons/fav/android-icon-192x192.png', 'assets/icons/fav'),
        ('assets/icons/fav/favicon-96x96.png', 'assets/icons/fav'),
        ('assets/icons/fav/ms-icon-144x144.png', 'assets/icons/fav'),
        ('assets/splash/splash.mp4', 'assets/splash'),
        ('assets/splash/splash.png', 'assets/splash'),
        ('assets/splash/splash_audio.wav', 'assets/splash'),
        ('icons/svgs', 'icons'),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tensorflow', 'tensorflow_hub',
        'torch', 'torchvision', 'torchaudio',
        'timm',
        'transformers',
        'onnxruntime', 'onnx',
        'pandas',
        'sklearn',
        'h5py',
        'cv2',
        'yt_dlp',
        'openpyxl',
        'lxml',
        'jinja2',
        'rich',
        'tqdm',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='StemPlayer',
	icon='assets/icons/icon.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='StemPlayer',
)
