APP_NAME = "StemPlayer"
APP_VERSION = "0.1.0"
APP_AUTHOR = "Pablo Jiménez"
APP_AUTHOR_EMAIL = "pablo.jimenez@users.noreply.github.com"
APP_GITHUB = "https://github.com/bay122/stemplayer"
APP_WEBSITE = "https://pablo-jimenez.site"
APP_LICENSE = "CC BY-NC-SA 4.0"
APP_DESCRIPTION = "Reproductor y mezclador de stems de audio con detección de tono, ajuste de pitch/tempo, generación ChordPro con IA y streaming de letras sincronizadas."
